config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'

  resources :users

  resources :tweets

  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Associations
  belongs_to :user
  belongs_to :tweet, counter_cache: true

  # Validations
  validates :body, presence: true, length: { maximum: 140 }
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  # Associations
  belongs_to :user
  has_many :comments, dependent: :destroy

  # Validations
  validates :body, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Associations
  has_many :tweets, dependent: :destroy
  has_many :comments, dependent: :destroy

  # Validations
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  validates :email, uniqueness: true
  validates :email, format: { with: VALID_EMAIL_REGEX }, allow_blank: false
  validates :username, presence: true, uniqueness: true
  validates :name, presence: true
  validates :password, length: { minimum: 6 }

  # Active Storage
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: %i[index show]
  def index; end

  def show; end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username name avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username name avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index; end

  def show; end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(body: params[:body])
    @comment.user = current_user
    if @comment.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(body: params[:body])
    @tweet.user = current_user

    if @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to root_path
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /user
  def index
    @user = User.all
  end

  # POST /user/:id
  def show
    @user = User.find(params[:id])
    @tweets = Tweet.where(user_id: params[:id]).find_each
  end

  # GET /user/new
  def new
    @user = User.new
    @roles = User.roles
  end

  # POST /user
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  # GET /user/:id/edit
  def edit
    @user = User.find(params[:id])
    @roles = User.roles
  end

  # PATCH /user/:id
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  # DELETE /user/:id
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :name, :avatar, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<div class="card justify-c l bold p-16">
  <h1>Edit Comment</h1>
</div>

 <div class="card">
    <%= form_with model: @comment, url: { action: "update" } do |form| %>
    <div class="card-inside center">
      <div class="txt-left">
        <p>Body</p>
      </div>
      <%= form.text_area :body ,placeholder: "Remember to think before write ..." ,class: "card-ar" %>
      <%= form.submit  "Edit",class: "btn btn--primary btn--fit-content" %>    
    </div>

    <% end %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetableIndividual</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header class="header">
        
        <%if current_user %>
          <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn--secondary btn--fit-content" %>
          <%= link_to "Logout", destroy_user_session_path ,method: :delete, class: "btn btn--primary btn--fit-content" %>
        <%else%>
          <%= link_to "Login", user_session_path, class: "btn btn--primary btn--fit-content" %>
        <%end %>
      </header>
      <main class="main">      
        <p class="flash-card"><%= notice %></p>
        <p class="flash-card"><%= alert %></p>
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/tweets/edit.html.erb
<div class="card justify-c l bold p-16">
  <h1>Edit Tweet</h1>
</div>
<div class="card">
  <%= form_with model: @tweet, url: { action: "update" } do |form| %>
    <div class="card-inside center">
      <div class="txt-left">
        <p>Body</p>
      </div>
      <%= form.text_area :body ,placeholder: "Remember to think before write ..." ,class: "card-ar" %>
      <%= form.submit  "Edit",class: "btn btn--primary btn--fit-content" %>
    </div>
  <% end %>
</div>

app/views/tweets/index.html.erb
<div class="card justify-c l bold p-16">
  <h1>Home</h1>
</div>
<%if current_user %>
  <div class="card mb-12">
    <%= image_tag current_user.avatar ,class: "card-img"%>
    <div class="card-contain">
    <%= form_with model: @tweet, url: { action: "create" } do |form| %>
      <div class="card-main">
        <%= form.text_area :body ,placeholder: "Remember to think before write ...", class: "card-area"%>
      </div>
      <div class="card-footer--end">
       <%= form.submit  "Tweet",class: "btn btn--primary btn--fit-content" %>
      </div>  
    </div>   
    <% end %>       
  </div>
<% end %>   

<% @tweets.each do |tweet| %>
  <div class="card">
    <div>
     <%= image_tag User.all.find_by(id: tweet.user_id).avatar, class: "card-img"%>
    </div>
    <div class="card-contain">
      <div class="card-main">
        <p class="m bold pt">
          <%= User.all.find_by(id: tweet.user_id).name%> <span class="reg st">@<%= User.all.find_by(id: tweet.user_id).username%></span>
              <span class="s reg st"><%= time_ago_in_words(tweet.created_at) unless tweet.created_at.blank? %> ago</span>
        </p>
        <p class="m reg"><%= tweet.body%></p>
      </div>
      <div class="card-footer">
        <div class="card-comments">
          <a href="<%=tweet_path(tweet)%>"><div><%= image_tag('comment.png')%></div></a>

          <p class="s reg st"><%= tweet.comments_count%></p>        
        </div>
        <%if current_user%>
          <%if current_user.id == tweet.user_id%>
         <div class="card-controls">
          <%= link_to tweet_path(tweet), method: :delete, data: { confirm: 'Do you want to delete it?' } do %>
            <%= image_tag "delete.png", alt: "delete" %>
          <% end %>
          <%= link_to edit_tweet_path(tweet) do %>
            <%= image_tag "edit.png", alt: "edit", class: "ml-12 flex align-end"   %>
          <% end %>
        </div>
          <%end %>
        <%end %>
      </div>
    </div>
  </div>
<% end %>

app/views/tweets/show.html.erb
<div class="card justify-c l bold p-16">
  <h1>Tweet detail</h1>
</div>
<div class="card mb-12">
  <div>
    <%= image_tag User.all.find_by(id: @tweet.user_id).avatar, class: "card-img"%>
  </div>
  <div class="card-contain">
    <div class="card-main">
      <p>
        <%= User.all.find_by(id: @tweet.user_id).name%> <span>@<%= User.all.find_by(id: @tweet.user_id).username%></span>
            <span><%= time_ago_in_words(@tweet.created_at) unless @tweet.created_at.blank? %> ago</span>
      </p>
      <p><%= @tweet.body%></p>
    </div>
    <div class="card-footer">
      <a href="<%=tweet_path(@tweet)%>"><div><%= image_tag('comment.png')%></div></a>
      <p><%= @tweet.comments_count%></p>
    </div>
  </div>
</div>

<%if current_user %>
<div class="card">
  <%if current_user%>
    <%= image_tag current_user.avatar ,class: "card-img"%>
  <%end%>
  <div class="card-contain">
  <%= form_with model: @comment, url: { action: "create" } do |form| %>
    <div class="card-main">
      <%= form.text_area :body ,placeholder: "This not create a comment :( ..." , class: "card-area" %>
    </div>
    <div class="card-footer--end">
      <%= form.submit  "Comment",class: "btn btn--primary btn--fit-content" %>
    </div>
  <% end %>
  </div>
</div>  
<% end %>

<% @tweet.comments.each do |comment| %>
  <div class="card">
    <%= image_tag User.all.find_by(id: comment.user_id).avatar,class: "card-img"%>
    <div class="card-contain">
      <div class="card-main">
        <p>
          <%= User.all.find_by(id: comment.user_id).name%> <span>@<%= User.all.find_by(id: comment.user_id).username%></span>
              <span><%= time_ago_in_words(comment.created_at) unless comment.created_at.blank? %> ago</span>
        </p>
      </div>
      <p><%= comment.body%></p> 
      <div class="card-footer">
        <div class="card-comments">        
        </div>
         <div class="card-controls">
            <%if current_user%>
              <%if current_user.id == comment.user_id%>
                <%= link_to comment_path(comment), method: :delete, data: { confirm: 'Do you want to delete it?' } do %>
                  <%= image_tag "delete.png", alt: "delete" %>
                <% end %>
                <%= link_to edit_comment_path(comment) do %>
                  <%= image_tag "edit.png", alt: "edit" %>
                <% end %>
              <% end %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>